<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<!-- NuGet Package Metadata -->
		<PackageId>Greenwaytech.PiholeApiClient</PackageId>
		<Version>0.1.10</Version>
		<Authors>Marcus Greenway</Authors>
		<Description>.NET Client for Pi-hole API</Description>
		<Copyright>Greenwaytech 2026</Copyright>
		<PackageTags>Pihole;ApiClient;DNS;Adblock</PackageTags>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/marcusmarkmus/Greenwaytech-PiHoleClient</PackageProjectUrl>
		<RepositoryUrl>https://github.com/marcusmarkmus/Greenwaytech-PiHoleClient</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Title>PiholeApiClient</Title>
		<PackageIcon>icon.png</PackageIcon>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Deterministic>true</Deterministic>
	</PropertyGroup>

	<PropertyGroup>
		<!-- XML Documentation -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<!-- Expose internals to test project -->
		<InternalsVisibleTo Include="Greenwaytech.PiholeApiClient.Test" />
	</ItemGroup>

	<ItemGroup>
		<!-- Include README and icon -->
		<None Update="README.md">
			<Pack>true</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="icon.png" Pack="true" PackagePath="\"></None>
	</ItemGroup>

	<ItemGroup>
		<!-- Dependencies -->
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.*" PrivateAssets="All" />
	</ItemGroup>

</Project>